#!/usr/bin/env bash

# -------------- Web servers

if [[ "$1" = "web-servers" || "$1" = "all" ]]; then
  kubectl apply -f nginx.yaml
  kubectl apply -f apache.yaml
  kubectl apply -f lighttpd.yaml
fi

# -------------- Databases

if [[ "$1" = "db" || "$1" = "all" ]]; then
  kubectl apply -f redis.yaml
  kubectl apply -f mongodb.yaml
  kubectl apply -f postgres.yaml
fi

# -------------- Expose everything

if [[ "$1" = "web-servers" || "$1" = "all" ]]; then
  for dep in $(kubectl get deployments -l type=web-server -o name); do
    kubectl expose $dep --type=NodePort --port=80
  done
fi
if [[ "$1" = "db" || "$1" = "all" ]]; then
  for dep in $(kubectl get deployments -l app=redis -o name); do
    kubectl expose $dep --type=NodePort --port=6379
  done
  for dep in $(kubectl get deployments -l app=mongo -o name); do
    kubectl expose $dep --type=NodePort --port=27017
  done
  for dep in $(kubectl get deployments -l app=postgres -o name); do
    kubectl expose $dep --type=NodePort --port=5432
  done
fi

# -------------- Check for YCSB

if [[ ! -f 'ycsb-0.17.0.tar.gz' ]]; then
  rm -rf ycsb-0.17.0
  curl -O --location https://github.com/brianfrankcooper/YCSB/releases/download/0.17.0/ycsb-0.17.0.tar.gz
  tar xfvz ycsb-0.17.0.tar.gz
fi
